/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
import "sst"
export {}
declare module "sst" {
  export interface Resource {
    "ElectricUrl": {
      "type": "sst.sst.Linkable"
      "url": string
    }
    "databaseUriLink": {
      "pooledUrl": string
      "type": "sst.sst.Linkable"
      "url": string
    }
    "electric-game-api": {
      "type": "sst.cloudflare.Worker"
      "url": string
    }
    "electricInfo": {
      "database_id": string
      "token": string
      "type": "sst.sst.Linkable"
    }
    "game-app": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
